kind: Secret
apiVersion: v1
metadata:
  name: <cluster>-cluster-secret
  namespace: team01
  labels:
    argocd.argoproj.io/secret-type: cluster
data:
  config: '{"bearerToken": ...' 
  name: <custer>
  server: https://api.<cluster>.<cluster-domain>:6443
type: Opaque
